CREATE TABLE USERS (
	U#		INT		NOT NULL,
	FNAME	 	VARCHAR(50)	NOT NULL,
	LNAME		VARCHAR(50)	NOT NULL,
	DOB		DATE		NOT NULL,
	BALANCE		FLOAT		NOT NULL,
	CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED ([U#] ASC)
);
